### ISSUE TITLE
typos in termux-prezto.sh

### ISSUE THREAD

**Issue by st42** [badtoyz/termux-prezto#1]
you have typos in line 17 of termux-prezto.sh

you have
ln -s $HONE/.zpresto/runcoms/zlogin $HOME/.zlongin

it should be
ln -s $HOME/.zpresto/runcoms/zlogin $HOME/.zlogin

**Comment by badtoyz** [comment]
Fixed

**Comment by st42** [comment]
you still have a typo in line 17 of termux-prezto.sh

you have
ln -s $HONE/.zpresto/runcoms/zlogin $HOME/.zlongin

it should be
ln -s $HOME/.zpresto/runcoms/zlogin $HOME/.zlogin

the variable $HOME is spelled $HONE

**Comment by badtoyz** [comment]
Fixed again
